nginx_exporter_version_env: 1.5.1

promtail_clients:
  - url: http://192.168.0.137:3100/loki/api/v1/push
promtail_scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: messages
          instance: "{{ ansible_facts['fqdn'] }}"
          __path__: /var/log/messages
      - targets:
          - localhost
        labels:
          job: nginx
          instance: "{{ ansible_facts['fqdn'] }}"
          __path__: /var/log/nginx/*.log