---
- name: Установка нужных пакетов
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - gpg

- name: Установить Python-зависимости для работы с Docker
  ansible.builtin.pip:
    name:
      - docker
      - requests
    state: present
  ignore_errors: true

- name: Установить зависимости Python через APT
  apt:
    name:
      - python3-docker
      - python3-requests
      - python3-venv
    state: present
  ignore_errors: true

- name: Добавление GPG-ключа для работы с репозиторием Docker
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Добавление докер репозиторий в локальный список
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Доп. обновление пакетов
  ansible.builtin.apt:
    update_cache: true

- name: Установка докера
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    state: present

- name: Запуск докера
  ansible.builtin.service:
    name: docker
    state: started
