---
all:
  children:
    prod:
      hosts:
        k3s:
          ansible_host: 192.168.0.116
        vault:
          ansible_host: 192.168.0.119
        proxy:
          ansible_host: 192.168.0.104
        monitoring:
          ansible_host: 192.168.0.137
    runners:
      hosts:
        docker_runner:
          ansible_host: 192.168.0.118
        infra_runner:
          ansible_connection: local
          ansible_host: 192.168.0.112
    main:
      hosts:
        main_host_proxmox:
          ansible_host: 192.168.0.110
