all:
  hosts:
    k3s:
      ansible_host: 192.168.0.116
    vault:
      ansible_host: 192.168.0.119
    # testing:
    #   ansible_host: 192.168.0.126
    # testingk3s:
    #   ansible_host: 192.168.0.132
    main_host_proxmox:
      ansible_host: 192.168.0.110