---
- name: Настройка vault
  hosts: vault

  roles:
    - setup_default_packages
    - vault_config

# playbook должен быть запущен после установки k3s
# Необходима переменная VAULT_ROOT_TOKEN как env при запуске playbook
