---
- name: Установка k3s в систему
  hosts: k3s

  roles:
    - setup_default_packages
    - role: create_ln_s
      vars:
        create_ln_s_links: "{{ install_k3s_mount_ln }}"
    - role: install_k3s
      vars:
        install_k3s_container_id: "{{ k3s_container_id }}"
