- name: Установка и настройка систем мониторинга
  hosts: monitoring

  roles:
    - setup_default_packages
    - install_docker
    - role: prometheus.prometheus.node_exporter
      vars:
        node_exporter_version: 1.10.2
    - install_monitoring