- name: Обновление dns записей
  hosts: all
  vars:
    dns_conf:
      - { regexp: '^#?DNS=',              line: 'DNS=8.8.8.8 1.1.1.1' }
      - { regexp: '^#?FallbackDNS=',      line: 'FallbackDNS=8.8.4.4 9.9.9.9' }
      - { regexp: '^#?Domains=',          line: 'Domains=~.' }
      - { regexp: '^#?DNSSEC=',           line: 'DNSSEC=no' }
      - { regexp: '^#?DNSOverTLS=',       line: 'DNSOverTLS=no' }
      - { regexp: '^#?MulticastDNS=',     line: 'MulticastDNS=no' }
      - { regexp: '^#?LLMNR=',            line: 'LLMNR=no' }
      - { regexp: '^#?Cache=',            line: 'Cache=yes' }
      - { regexp: '^#?DNSStubListener=',  line: 'DNSStubListener=yes' }
  tasks: 
    
    - name: Замена текста (DNS) 
      lineinfile:
        path: '/etc/systemd/resolved.conf'
        regexp: '{{ item.regexp }}'
        line: '{{ item.line }}'
      loop: "{{ dns_conf }}"

    - name: Рестарт службы резолва днс
      systemd_service:
        name: systemd-resolved
        state: restarted