---
vault_initialize_directory_configs:
  - /etc/vault
  - /var/lib/vault

vault_initialize_download_data:
  domain: http://192.168.0.104/static
  version_vault: vault_1.21.1_linux_amd64.zip

vault_initialize_adress_connect: http://127.0.0.1:8201

vault_initialize_file_path: /tmp/vault.zip
vault_initialize_config_path: /etc/vault/config.hcl
