---
- name: Обновляем пакеты
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Установка curl
  ansible.builtin.apt:
    name: curl
    state: present

- name: Установка unzip
  ansible.builtin.apt:
    name: unzip
    state: present

- name: Установка python
  ansible.builtin.apt:
    name: python3-pip
    state: present
