# Временное решение, хранить тут секрет в таком виде нельзя, будет переделано
apiVersion: v1
kind: Secret
metadata:
  name: docker-login-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImFXZHZjbVpwYkdsdU9tUmphM0pmY0dGMFgzSTRlVTVJZEhGMmJWQk9VbXRHVmtWSk5XcG1NemxUWTFsV09BPT0iCgkJfQoJfQp9
