apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app
  labels:
    app.kubernetes.io/name: myingress
  annotations:
    # Формат: <namespace>-<middleware-name>@kubernetescrd
    traefik.ingress.kubernetes.io/router.middlewares: default-replacepathregex@kubernetescrd
spec:
  rules:
  - host: training-program.ru
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/api/"
        backend:
          service:
            name: gateway-cluster-ip
            port: 
              number: 3000
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: frontend-cluster-ip
            port: 
              number: 80

