apiVersion: apps/v1
kind: Deployment
metadata:
  name: knowledge-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: knowledge
  
  template:
    metadata:
      labels:
        service: knowledge
    spec:
      containers:
        - name: knowledge
          image: igorfilin/knowledge-micro-service:v1.0
          imagePullPolicy: Always
          env:
            - name: 'JWT_SECRET'
              valueFrom:
                secretKeyRef:
                  name: k3s-external-secret
                  key: JWT_SECRET
            - name: 'BD_PORT'
              valueFrom:
                secretKeyRef:
                  name: k3s-external-secret
                  key: BD_PORT
            - name: 'BD_HOST'
              valueFrom:
                secretKeyRef:
                  name: k3s-external-secret
                  key: BD_HOST
            - name: 'BD_PASSWORD'
              valueFrom:
                secretKeyRef:
                  name: k3s-external-secret
                  key: BD_PASSWORD
            - name: 'BD_USERNAME'
              valueFrom:
                secretKeyRef:
                  name: k3s-external-secret
                  key: BD_USERNAME
            - name: 'BD_DATABASE'
              valueFrom:
                secretKeyRef:
                  name: k3s-external-secret
                  key: BD_DATABASE
            - name: 'SECRET_REGISTER_KEY'
              valueFrom:
                secretKeyRef:
                  name: k3s-external-secret
                  key: SECRET_REGISTER_KEY
            - name: 'EMAIL_USERNAME'
              valueFrom:
                secretKeyRef:
                  name: k3s-external-secret
                  key: EMAIL_USERNAME
            - name: 'EMAIL_PASSWORD'
              valueFrom:
                secretKeyRef:
                  name: k3s-external-secret
                  key: EMAIL_PASSWORD
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "200m"
      imagePullSecrets:
        - name: docker-login-secret
