{{- with Values.middlewares.replacepath}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
 
spec:
  replacePathRegex:
    regex: {{ .regex }}
    replacement: {{ .replacement }}
{{- end }}