apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.users.cluster_name }}
spec:
  type: ClusterIP
  selector:
    {{ toYamlPretty .Values.users.label }}
  ports:
  - port: {{ .Values.users.cluster_port }}
    targetPort: {{ .Values.users.container_port }}
