apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.users.deployment_name }}
spec:
  replicas: {{ .Values.users.replicas }}
  selector:
    matchLabels:
      {{ toYamlPretty .Values.users.label }}
  
  template:
    metadata:
      labels:
        {{ toYamlPretty .Values.users.label }}
    spec:
      containers:
        - name: users
          {{- with .Values.users.image }}
          image: "{{ .repository }}:{{ .version }}"
          {{- end }}
          imagePullPolicy: {{- range .Values.users.imagePullPolicy }}
          env:
          {{- range .Values.users.envs }}
            {{- $data := dict "name" .Values.backend_secret "env" }}
            {{- include "env.template" $data | indent 12 }}
          {{- end }}
          resources:
            limits:
              {{ .Values.users.limits }}
            requests:
              {{ .Values.users.requests }}
          ports:
          - containerPort: {{ .Values.users.container_port }}
      imagePullSecrets:
        {{- .Values.docker_login_secret | indent 8 }}
