
auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /opt/loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

compactor:
  working_directory: /opt/loki/compactor

schema_config:
  configs:
  - from: 2025-12-14
    store: boltdb-shipper
    object_store: filesystem
    schema: v13
    index:
      prefix: index_
      period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /opt/loki/index
    cache_location: /opt/loki/index_cache
  filesystem:
    directory: /opt/loki/chunks

limits_config:
  retention_period: 24h
  allow_structured_metadata: false