global:
  scrape_interval: 5s
  

scrape_configs:
  - job_name: node
    static_configs:
    - targets: ['192.168.0.137:9100']
  - job_name: 'nginx'
    static_configs:
    - targets: ['192.168.0.104:9113']

storage:
  tsdb:
    retention:
      time: 1d
      size: 1GB